name: Health Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Run health checks
      run: |
        echo "Running application health checks..."
        
        # Check if critical files exist
        if [ ! -f "package.json" ]; then
          echo "❌ package.json missing"
          exit 1
        fi
        
        if [ ! -f "README.md" ]; then
          echo "❌ README.md missing"
          exit 1
        fi
        
        echo "✅ Critical files check passed!"
        
        # Try to build the project
        npm run build
        echo "✅ Build successful!"
        
        echo "✅ Health check completed successfully!"
    
    - name: Test application components
      run: |
        echo "Testing critical functionality..."
        # Run type checking if available
        npm run type-check || echo "Type checking not available, skipping..."
        
        # Run tests
        npm test
        
        echo "✅ Component tests completed!"
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Health Check Failed - ' + new Date().toISOString(),
            body: 'Automated health check failed. Please investigate.\n\nWorkflow run: ' + context.serverUrl + '/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.runId,
            labels: ['bug', 'automated', 'health-check']
          })